version: '3'
services:
  app:
    container_name: maker
    restart: always
    build: .
    environment:
      - TOKEN="HXJg1h4KZLskSSWakM2dI53vrIPUSZRL"
    ports:
      - '8080:8080'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'